Fixed  error C3791: 'this' cannot be explicitly captured (#19280)
* Fixed  error C3791: 'this' cannot be explicitly captured when the default capture mode is by copy (=)
* Fixed error C4855: implicit capture of 'this' via '[=]' is deprecated in '/std:c++20'
------

Signed-off-by: Luis Sempé <58790905+lsemp3d@users.noreply.github.com>